# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pj',
                'doc_host': 'https://kitled.github.io',
                'git_url': 'https://github.com/kitled/pj',
                'lib_path': 'pj'},
  'syms': {'pj.core': {'pj.core.foo': ('core.html#foo', 'pj/core.py')}}}
